### ISSUE TITLE
Return display order with ranked abundance

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#13]
The ordering is getting all wonky when we send results to plot.data because somewhere inside it sorts the boxes. End result is they come out alphabetically instead of ordered by their rank.

Either we need to 
1. Send displayOrder along with the outputted json or compute config that then the front end reads - or - 
2. Have plot.data respect ordering of collection vars when they come in.

When writing the plot.data collection code, i recall 2 being really difficult. If we go with 1, should name it the same as the displayOrder annotation for categorical vars

**Comment by asizemore** [comment]
@d-callan

**Comment by d-callan** [comment]
the recent pie plot has a similar concept.. a new attr called 'rankedValues'. think this should follow suit.

that means well be taking option 1 above, and it will require some updates to any plots in plot.data that take ranked collection values (box and scatter i think?) at a minimum. youll have to update the api in the data service accordingly as well, and i might start there so we are confident we know what we want as our final result before starting implementing anything.

**Comment by d-callan** [comment]
also, you should feel free to propose updates to pie as needed to make sure these two similar needs are represented consistently. and once were sure we have what we need for box, scatter and pie we should think about if the concept is able to be more generally applied to other plot components or if wed like to stop there for now. but i think those questions can be addressed as part of the data service PR.

**Comment by asizemore** [comment]
Works for me!!

**Comment by asizemore** [comment]
Will be handled on the front end. See https://github.com/VEuPathDB/web-eda/issues/1084

Nothing to QA
