### ISSUE TITLE
beta div: Some collection variables have missing values in the distance matrix 

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#31]
Possibly two rows are all zeros so their distance is missing? 

<img width="1238" alt="Screen Shot 2022-12-19 at 9 17 04 AM" src="https://user-images.githubusercontent.com/11710234/208445898-7c1ebf41-012a-4c66-83c5-f02ef284e1ee.png">

Output from Rserve:
```
Error in eigen(delta1) : infinite or missing values in 'x'

In addition: Warning messages:

1: replacing previous import ‘veupathUtils::toJSON’ by ‘jsonlite::toJSON’ when loading ‘plot.data’ 

2: In fread("beta_div_input", select = c(OBI_0002623.MetagenomicSequencingAssay_stable_id = "double",  :

  Attempt to override column 1 <<OBI_0002623.MetagenomicSequencingAssay_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.

3: In fread("beta_div_input", select = c(OBI_0002623.MetagenomicSequencingAssay_stable_id = "double",  :

  Attempt to override column 2 <<EUPATH_0000609.Sample_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.

4: In fread("beta_div_input", select = c(OBI_0002623.MetagenomicSequencingAssay_stable_id = "double",  :

  Attempt to override column 3 <<EUPATH_0000096.Participant_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.

5: In vegan::vegdist(df[, -..allIdColumns], method = method, binary = TRUE) :

  you have empty rows: their dissimilarities may be

                 meaningless in method “jaccard”

6: In vegan::vegdist(df[, -..allIdColumns], method = method, binary = TRUE) :

  missing values in results
```

**Comment by asizemore** [comment]
Also got this warning in MORDOR Phylum

**Comment by asizemore** [comment]
@sweverschulman do you know if FARMM was reloaded or modified to remove its collection variables? Instead of getting the error above, I get a "No collections available" error. 
(This taught me we should handle the no collections error better anyways 😄 )

**Comment by d-callan** [comment]
ive been doing some digging here, and i am now fairly confident the only way this could happen is if we have samples that have no values for any species (meaning we impute 0 for all species for a sample). that seems very suspicious however...

**Comment by d-callan** [comment]
SRR9843658 appears to be such a sample for the MORDOR phylum case for ex. it seems that we dont have assay data for this sample (perhaps it failed during the workflow?) but we do have sample and participant data. that means the merge service still gives us ancestor IDs for that sample, but all the values for all the requested variables are NULL. i think this package needs to learn to ignore such samples for the beta div method at the very least, but possibly other methods as well.

**Comment by d-callan** [comment]
the other option i suppose is to not load anything for failed samples at all?

**Comment by d-callan** [comment]
hmmmmm... thinking some more, maybe we do both? if a sample fails ALL assays, then dont load anything for it? but if it fails for one assay but not another, load what we have and tell the compute to ignore it where needed? the ux on this could get tricky, bc it seems important to let users know when a sample failed maybe?

**Comment by d-callan** [comment]
one final note on this. for mordor, 600 samples have sample or participant data, 595 have wgs pathway data and 574 have wgs rel abund data (due to failures). we currently have no way to tell users about the failures, and instead suggest we have 595 samples w rel abund data.

**Comment by asizemore** [comment]
Discussed last week on mbio call, @jbrestel and @jaycolin are planning to work on this with some data loading updates. Let's keep this issue open just to make sure we don't forget about it!

**Comment by jaycolin** [comment]
The assay data for specified SRRs in 4 studies has been removed, as instructed (MORDOR, FARMM, NICUNEC, NICUDischarge (preterm 2)

**Comment by d-callan** [comment]
thanks @jaycolin. i think we should close this ticket. we can open new tickets for the issues w the pathway data etc. reason being, they are likely to have different solutions than the taxa abundance data we handled here, and also they are for b63 rather than 62. thoughts @asizemore ?

**Comment by asizemore** [comment]
Thanks @jaycolin ! Yes @d-callan that's a good idea. I'll open a new ticket.

**Comment by asizemore** [comment]
This has been deployed and QA-ed. Moving to complete
