### ISSUE TITLE
Correlations handle missing metadata

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#59]
Samples may not all have data for assays (not the case for mbio, but it's possible in general), and they definitely dont all have data for each metadata var. For example, in bonus 8 part rep measures are missing data for recumbent length. Currently if there's missing data in var A, then all the correlation coefs for var A vs all-other-vars will be na. We filter all empty edges out in the viz so those vars just get dropped entirely. 

Ideally we'd compute the correlation in an elegant way that handles missing data. One idea i had was to then return the number of samples with data (n) along with the correlation coef? That's nice for a table, but not great for the bipartite viz because we don't want to show tooltips for edges (the natural place to put n). But on the other other hand if we show corr results in a heatmap then hovering over a cell _would_ be a good place for n. So yeah maybe sending back n for each link is the best strategy...

**Comment by d-callan** [comment]
id think for each edge wed want to know:

**Comment by d-callan** [comment]
heres an image from live clinepi as an ex. our scatter could have the number of contributing points in the title, and we could reuse the completeness table back and front end code hopefully as well. ignore the birds eye bar i think.

![scatter-missingness](https://github.com/VEuPathDB/microbiomeComputations/assets/53306535/473656ff-4dc4-4206-9c37-c1bb29f405b7)

**Comment by d-callan** [comment]
hmmm. sorry im also realizing for clarity i should probably say that i think whatever request we make for the scatterplot should get this info for free. so im inclined to wait for this ticket until we integrate the scatterplot into the correlation viz.

**Comment by asizemore** [comment]
To make sure i understand, is your suggestion to not handle NAs until we do the scatterplot work, which would mean we can only compute correlation with metadata that has all values present? Or is your proposal to not worry about sending back all of the extra data about missingness until we do the scatterplot?

**Comment by d-callan** [comment]
i modified the R to use complete cases to find the correlation coefficients as a first step, but i dont think we want to report how many samples were complete etc yet.

**Comment by d-callan** [comment]
is this still a must have?

**Comment by asizemore** [comment]
I think this was solved by adding the complete cases fn. I'm going to close the issue, and see if any bug bubbles up again that makes us reopen it.
