### ISSUE TITLE
Correlations: pre-filter features before performing calculation

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/microbiomeComputations#69]
Examples might be to filter taxa so that only those are kept which are seen in 50% of samples or more, or filter pathways by coverage, or filter either by abundance, or probably other ideas we should consider as well...

whatever we decide, we should be able to support w literature and add to user-facing documentation, OR add user-controls for

**Comment by asizemore** [comment]
We're a go on pre-filtering on the backend and writing about it in our user documentation. We should remove variables that don't meet a min proportion of non-zero values. @d-callan did you say you usually saw values around 50% for the min proportion?
