### ISSUE TITLE
Correlation handle dates

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#71]
ECAM has a date var. Neat!

Let's add support for dates to the corr functions

**Comment by d-callan** [comment]
so im surprised this is a must-have.. ive spent a bit of time thinking about it just now and have some questions/ concerns:
1. this doesnt seem super straightforward. we have to update this R package to support including metadata on variables so we actually know when we have dates. the only other options i can think of feel too hacky tbh. do i misunderstand?
2. assuming we can reliably identify dates, the best we can do is probably convert to a number and then run the correlation. are we ok w this?
3. if we do this, at best were answering questions about general trends over time without being able to identify time periods of interest,  longitudinal trends across participants, two different variables being correlated over time, etc. is this still useful?
4. it seems like there are very few date vars in mbio, so idk how much benefit wed get from this. is it worth the cost?
5. can we maybe start the conversation at 'what kinds of temporal questions would we like to answer?' and 'is a correlation app the right place to answer those questions?'

**Comment by asizemore** [comment]
You're right this isn't straightforward anymore. There was a point where the corr functions accepted variableMetadata already but i forgot that's not how they work now. So i agree with taking this off the must have list! And i'll write down 3-5 to be added to our next meeting with dan!
