### ISSUE TITLE
Correlation returning NaN??

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#73]
Found this while working on another issue

<img width="1392" alt="Screen Shot 2023-12-19 at 6 34 24 AM" src="https://github.com/VEuPathDB/microbiomeComputations/assets/11710234/826be5ac-1774-4750-b088-854ad2c2712d">

A big problem is that we're still rendering those edges! Possibly we're doing the number-string transformation wrong somewhere? Will have to check...

**Comment by d-callan** [comment]
is the correlation app currently displaying a count of how many records it represents? im wondering if the sample size here is small?

**Comment by asizemore** [comment]
No it's not displaying a count of how many records it represents per edge. Once we have the helper scatter we'll have that info!
What if we set a min number of records each edge must use? Like a minimum "n". The computation can send that info to the frontend and the viz can add that info to the plot title. It could even be another filter if we wanted.

**Comment by d-callan** [comment]
Somewhere I think I made a ticket about prefiltering variables, and if this idea isn't in that ticket yet I think it should be.

**Comment by d-callan** [comment]
rare taxa where only a small number of samples have non-zero values are producing NaNs. to me, that is a valid result. id be in favor of letting the backend be, and improving handling frontend.

**Comment by d-callan** [comment]
also, for posterity, the issue about pre-filtering features is here https://github.com/VEuPathDB/microbiomeComputations/issues/69
