### ISSUE TITLE
Diff abund returns pointIDs but no statistics

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/microbiomeComputations#80]
I'd guess that there are never enough non-zero samples to get a good effect size out of, but worth confirming.

Related, if no effect size or pval is returned, should we return that point at all? 

UPDATE:
The compute isn't _totally_ broken. I can get a successful compute with different inputs such as diet. So the no data returned is actually specific to the inputs
<img width="1834" alt="Screen Shot 2024-02-01 at 6 57 30 AM" src="https://github.com/VEuPathDB/microbiomeComputations/assets/11710234/8ee6d5aa-1bdb-47bb-b40d-569ea5bd2da9">

**Comment by asizemore** [comment]
<img width="1012" alt="Screen Shot 2024-02-01 at 6 58 22 AM" src="https://github.com/VEuPathDB/microbiomeComputations/assets/11710234/61e3a8c6-8afc-41fa-bf2e-90c06f590b40">

Example to prove to ourselves it does work sometimes

**Comment by asizemore** [comment]
@d-callan seems like we should just drop any points that don't have stats from the response. That's basically what we do for correlation. Do you see a reason to do otherwise here?

**Comment by d-callan** [comment]
Correlation returns NA explicitly and the data service chooses to ignore those on a per viz basis. I like that a bit better, particularly since we prefilter features in both places. This doesn't seem to do that, but maybe should, if I understand right? Do any points have stats? Have we confirmed the cause of the missing stats?

**Comment by d-callan** [comment]
i spent some time looking at this, and its a data issue. the case or control variable is.... odd. if you look at it in the browse and subset tab it has values TRUE and FALSE which dont make sense. and only one participant has a value of TRUE, which is just strange and makes me wonder if thats accurate. and worse, if you filter to that TRUE value you see that that participant doesnt have metabolomics data. so the compute fails bc there is functionally only one value for that variable for the subset in question...

**Comment by d-callan** [comment]
i suppose this should result in a failed compute? rather than empty one? deseq i know checks for more than one value for the variable in question and will err if it doesnt find them. we could do something similar for maaslin manually.
